version: '3'

services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    env_file: 
      - .env
    volumes:
      - sails-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  sails-data: